{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hr-enterprise-api.fullname" . }}
  labels:
    {{- include "hr-enterprise-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hr-enterprise-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    # Allow all egress traffic (can be restricted as needed)
    - {}
{{- end }}