apiVersion: v1
kind: Service
metadata:
  name: mcp-weather
  namespace: llama-stack-mcp-demo
spec:
  selector:
    app: mcp-weather
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP 