{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama-stack.fullname" . }}-config
  labels:
    {{- include "llama-stack.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{ .Values.llamaStack.configFile }}: |
    inference_providers:
      {{- range .Values.inference.endpoints }}
      - provider_id: {{ .name }}
        provider_type: remote::ollama
        config:
          url: {{ .url }}
          model: {{ .model }}
      {{- end }}

    mcp_stores:
      {{- range .Values.mcpServers }}
      - uri: {{ .uri }}
        name: {{ .name }}
        description: {{ .description }}
      {{- end }}

    agents_store:
      provider_id: inline
      provider_type: inline
      config: {}

    memory_stores:
      - provider_id: inline
        provider_type: inline
        config: {}

    safety_stores:
      - provider_id: inline
        provider_type: inline
        config: {}

    telemetry:
      enabled: false

    server:
      host: {{ .Values.env.LLAMA_STACK_HOST }}
      port: {{ .Values.env.LLAMA_STACK_PORT }}
{{- end }}